import Link from 'next/link';import Image from 'next/image';import Reveal from '@/components/Reveal';import ContactForm from '@/components/ContactForm';
const services=[['01','E-commerce & Marketplace Consulting','Seller onboarding, listings, catalog optimization, inventory, promotions, performance and account health.'],['02','Digital Marketing & Performance Growth','Meta, Google, YouTube, lead generation, e-commerce campaigns, remarketing and analytics.'],['03','Website & Technology Solutions','Shopify, WordPress, custom websites, landing pages, payment and CRM/API integrations.'],['04','Business Development & Advisory','Planning, go-to-market, transformation, positioning, revenue and sales strategy.'],['05','Brand Development & Positioning','Practical brand and growth strategy for stronger market presence.'],['06','Business Automation & Digital Transformation','Technology-led solutions that improve efficiency and support sustainable growth.']];
const industries=['Food & Beverage','Fashion & Lifestyle','Beauty & Personal Care','Health & Wellness','Home & Living','FMCG & Consumer Products','D2C Brands','Manufacturing & Retail'];
export default function Home(){return <>
<section className="hero"><div className="heroCopy"><div className="eyebrow">HUBOOZE CONSULTANCY SERVICES</div><h1>Turn complexity into <em>business growth.</em></h1><p className="lead">HCS helps startups, MSMEs, D2C brands, manufacturers and established enterprises grow through e-commerce, performance marketing, technology and strategic consulting.</p><div className="actions"><Link className="btn dark" href="/services">Discover what we do →</Link><Link className="under" href="/contact">What's on your mind? ↗</Link></div></div><div className="heroArt"><div className="ring ring1"/><div className="ring ring2"/><div className="ring ring3"/><div className="heroPanel"><div className="eyebrow">HCS GROWTH ENGINE</div><h3>Enterprise thinking.<br/><span className="serif">Practical execution.</span></h3>{['E-commerce','Performance','Technology','Advisory'].map((x,i)=><div className="statline" key={x}><span>{x}</span><b>0{i+1}</b></div>)}</div></div></section>
<Reveal><section className="section split"><div>01</div><div><div className="eyebrow">WHO WE ARE</div><h2>Enterprise-level expertise, <span className="serif">made accessible.</span></h2></div><p className="muted">HCS is the B2B consulting division of Hubooze. We simplify digital transformation with practical, affordable and result-oriented solutions.</p></section></Reveal>
<Reveal><section className="section"><div className="head"><div><div className="eyebrow">WHAT WE DO</div><h2>Capabilities that create momentum.</h2></div><Link className="under" href="/services">View all services ↗</Link></div><div className="cards">{services.map(([n,t,d],i)=><article className={'card '+(i===0?'featured':'')} key={n}><div>{n}</div><h3>{t}</h3><p>{d}</p><Link href="/services">Explore →</Link></article>)}</div></section></Reveal>
<Reveal><section className="section black"><div className="industryLayout"><div><div className="eyebrow">INDUSTRIES</div><h2>Deep context.<br/><span className="serif">Real-world growth.</span></h2><p className="muted">HCS serves consumer, commerce, manufacturing and distribution businesses with integrated solutions.</p><Link className="btn light" href="/industries">Explore industries →</Link></div><div className="industryList">{industries.map((x,i)=><Link className="industry" href="/industries" key={x}><span>0{i+1}</span>{x}<b>↗</b></Link>)}</div></div></section></Reveal>
<Reveal><section className="section"><div className="head"><div><div className="eyebrow">CUSTOMER VALUE</div><h2>Real services. Real execution.</h2></div></div><div className="showcase"><article className="show"><Image src="/assets/amazon-management.jpg" alt="HCS Amazon management brochure" width={900} height={1100}/><div className="showCopy"><h3>E-commerce Management</h3><p>Brand store design, A+ listing creation, product listings, specialist support, SAFE-T claims, returns, ad campaign support and logistics issue resolution are featured in the supplied HCS brochure.</p><Link className="under" href="/contact">Discuss the service ↗</Link></div></article><article className="show"><Image src="/assets/business-solutions.jpg" alt="HCS business solutions brochure" width={900} height={1100}/><div className="showCopy"><h3>Affordable Business Solutions</h3><p>The supplied brochure presents a subscription concept plus website, SEO and brand consultancy services. Confirm live pricing before publishing.</p><Link className="under" href="/contact">Get current pricing ↗</Link></div></article></div></section></Reveal>
<Reveal><section className="story"><div className="storyVisual"><div><div className="eyebrow">HCS × HUBOOZE</div><h3>Consulting backed by<br/>real e-commerce operations.</h3></div></div><div className="storyCopy"><div className="eyebrow">OUR ECOSYSTEM</div><h2>Commerce + technology + <span className="serif">consulting.</span></h2><p>HCS operates as the consulting and business solutions division of the Hubooze ecosystem, combining consulting, e-commerce operations, technology and digital marketing.</p><Link className="btn dark" href="/about">Discover HCS →</Link></div></section></Reveal>
<Reveal><section className="section"><div className="head"><div><div className="eyebrow">INSIGHTS</div><h2>Ideas for ambitious businesses.</h2></div><Link className="under" href="/insights">Explore insights ↗</Link></div><div className="insights">{[['E-COMMERCE','Marketplace management for growing brands'],['PERFORMANCE','Performance marketing that connects to revenue'],['TECHNOLOGY','Choosing the right website platform']].map(([tag,t])=><article className="insight" key={t}><div className="tag">{tag}</div><h3>{t}</h3><p className="muted">Practical HCS perspectives for businesses navigating digital growth.</p><Link href="/insights">Read more →</Link></article>)}</div></section></Reveal>
<Reveal><section className="section"><div className="head"><div><div className="eyebrow">OUR CLIENTS</div><h2>Growing with ambitious brands.</h2></div></div><div className="pills">{['B77 Lifestyle','Dihas Kitchen','Almond House','Tanza Tea','Chique','Hubooze','Agniya Food','Shroomnest Blend Coffee','Authentara','The Shimmer House','Gaiabay'].map(x=><span className="pill" key={x}>{x}</span>)}</div></section></Reveal>
<section className="careers"><div><div className="eyebrow">CAREERS AT HCS</div><h2>Build your<br/><span className="serif">next chapter.</span></h2></div><div><p className="lead">The careers section is structured for your real vacancies, culture details and hiring process.</p><Link className="btn dark" href="/careers">Explore careers →</Link></div></section>
<section className="contact"><div><div className="eyebrow">CONTACT HCS</div><h2>What's on<br/>your mind?</h2><p className="muted">+91 90049 18382<br/>team.support@hubooze.in</p></div><ContactForm/></section>
</>}
